#!/bin/sh
cd ${0%/*} || exit 1    # run from this directory
set -x

./libs/Allwclean
./solvers/Allwclean
./utilities/Allwclean


# ----------------------------------------------------------------- end-of-file
