#!/bin/sh
cd ${0%/*} || exit 1    # run from this directory
set -x

./thermophysicalModels/Allwclean
./regionModels/Allwclean
wclean libso lagrangian/basicNew
wclean libso lagrangian/intermediateNew


# ----------------------------------------------------------------- end-of-file
