#!/bin/sh
cd ${0%/*} || exit 1    # run from this directory
set -x

wmake libso regionModel
wmake libso pyrolysisModels


# ----------------------------------------------------------------- end-of-file
