#!/bin/sh
cd ${0%/*} || exit 1    # run from this directory
set -x

wclean libso regionModel
wclean libso pyrolysisModels


# ----------------------------------------------------------------- end-of-file
