#!/bin/sh
cd ${0%/*} || exit 1    # run from this directory
set -x

wmake libso solid
wmake libso basicSolid
wmake libso chemistryModel


# ----------------------------------------------------------------- end-of-file
