#!/bin/sh
cd ${0%/*} || exit 1    # run from this directory
set -x

wclean libso solid
wclean libso basicSolid
wclean libso chemistryModel


# ----------------------------------------------------------------- end-of-file
