#!/bin/sh
#set -x 

# Source tutorial run functions
. $WM_PROJECT_DIR/bin/tools/RunFunctions

# Set application name
application="fireFoam"

./Allclean

runApplication blockMesh

# create faceZones
setSet -batch system/faceZone.batch
rm constant/polyMesh/sets/f0
setsToZones  

rm log.* 

# Run
runApplication $application 

# -----------------------------------------------------------------------------
