#!/bin/sh
cd ${0%/*} || exit 1    # run from this directory
set -x

wclean libso additionalReactionsNew
wclean libso reactionThermoNew
wclean libso combustionModelsSpecies
wclean libso chemistryModelNew
./basicSolidThermo/Allwclean


# ----------------------------------------------------------------- end-of-file
