#!/bin/sh
cd ${0%/*} || exit 1    # run from this directory
set -x

wmake libso additionalReactionsNew
wmake libso reactionThermoNew
wmake libso SLGThermo
wmake libso combustionModelsSpecies
wmake libso chemistryModelNew
wmake libso radiationModelNew
./basicSolidThermo/Allwmake


# ----------------------------------------------------------------- end-of-file
