#!/bin/sh
cd ${0%/*} || exit 1    # run from this directory
set -x

./extrudeToRegionMesh/Allwmake
./mapFields/Allwmake
./decomposeParPyr/Allwmake


# ----------------------------------------------------------------- end-of-file
