#!/bin/sh
cd ${0%/*} || exit 1    # run from this directory
set -x

wclean libso diffusionCombustionThermophysicalModels
wclean libso fvPatchFields
wclean

# ----------------------------------------------------------------- end-of-file
