#!/bin/sh

# Source tutorial run functions
. $WM_PROJECT_DIR/bin/tools/RunFunctions

./Allclean
./Allrun.pre

# Set application name
application="fireFoam"

runApplication decomposeParPyr -region panelRegion
runApplication decomposePar

runParallel $application 2

#runApplication reconstructPar


# -----------------------------------------------------------------------------
