#!/bin/bash

# Source tutorial run functions
. $WM_PROJECT_DIR/bin/tools/RunFunctions

./Allclean
./Allrun.pre

# Set application name
application="fireFoam"

runApplication decomposeParPyr -region panelRegion
runApplication decomposePar

#runParallel $application 2
mpirun -np 2 $application -parallel < /dev/null > log.$application 2>log.$application.err

#runApplication reconstructPar


# -----------------------------------------------------------------------------
