#!/bin/sh
cd ${0%/*} || exit 1    # run from this directory
set -x

wmake libso diffusionCombustionThermophysicalModels
wmake libso fvPatchFields
wmake

# ----------------------------------------------------------------- end-of-file
