#!/bin/sh
cd ${0%/*} || exit 1    # run from this directory
set -x

./thermophysicalModels/Allwmake
./regionModels/Allwmake
wmake libso lagrangian/basicNew
wmake libso lagrangian/intermediateNew


# ----------------------------------------------------------------- end-of-file
