#!/bin/sh
cd ${0%/*} || exit 1    # run from this directory
set -x

./extrudeToRegionMesh/Allwclean
./decomposeParPyr/Allwclean


# ----------------------------------------------------------------- end-of-file
